version: '3.7'

services:
  beego:
    container_name: beego
    build:
      dockerfile: ./docker/Dockerfile.local
      context: .
    restart: always
    ports:
      - "8304:8080"
      - "8088:8088"
    volumes:
      - ./api:/go/src/api:cached
      - ./api/.env.local:/go/src/api/.env:cached
    environment:
      APP_ENV: local
    networks:
      network-horeca:
        aliases:
          - beego.local
      network-graylog:
    healthcheck:
      test: curl -f http://beego.local
      start_period: 30s
      interval: 30s
      timeout: 15s
      retries: 3

networks:
  network-horeca:
    external: true
  network-graylog:
    external: true